name: '🔂 Surge PR Preview 1'
description: 'Preview website in surge.sh for every pull request'
author: 'hunghg255'
branding:
  icon: 'monitor'
  color: 'yellow'

runs:
  using: 'node16'
  main: 'lib/index.js'

inputs:
  surge_token:
    description: 'surge.sh token'
    default: '3e5401b357d5f3b46ea4a6a9e28f1ebb'
  github_token:
    description: 'github token'
    required: true
    default: ${{ github.token }}
  build:
    description: 'build scripts'
    default: |
      npm install
      npm run build
    required: false
  dist:
    description: 'dist folder to deploy'
    default: 'public'
    required: false
  failOnError:
    description: 'Set `failed` if a deployment throws error'
  teardown:
    description: 'Determines if the preview instance will be torn down on PR close'
    default: 'false'
    required: false
  preview_branch:
    description: 'Determines if the current branch is a preview branch'
    default: 'false'
    required: false

outputs:
  preview_url:
    description: 'The url for the related PR preview'
