name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: hunghg255/changeloggithub-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          from_branch: 'changelog-action'
          to_branch: 'master'
